### ISSUE TITLE
Syntax error on Ruby 2.2 after upgrading to 3.1

### ISSUE THREAD

**Issue by henrik** [splitrb/split#494]
This:

```
SyntaxError: /var/lib/jenkins/.bundle/auctionet/ruby/2.2.0/gems/split-3.1.0/lib/split/helper.rb:13: syntax error, unexpected '.'
...it::configuration.experiments&.dig(experiment.name.to_sym,:c...
...                               ^
```

This is new Ruby syntax AFAIK. The gem is doced as supporting 1.9.2+, and that's what the gemspec says.

Travis could be set up to cover all supported Ruby versions to catch these.

**Comment by andrew** [comment]
@henrik happy to merge a pull request to fix this if you'd like, and if you want to add 1.9.2 to the matrix in `.travis.yml` we can add the regression testing back in

**Comment by henrik** [comment]
Hi! I could maybe make a PR later today if I find the time, but feel free to do it without me if you like :)

**Comment by iwz** [comment]
I'm running into this on Ruby 2.2.7.

https://github.com/splitrb/split/commit/ccff6dc51b6869e2deddf7957770243a45e97ee6#diff-71d321a2380b5573f6b327b81456f439R13 Is the culprit, as noted above.

**Comment by patbl** [comment]
Rails 4.2 requires Ruby 1.9.3+, and 4.2 is the earliest version of Rails that Split is tested with.

I think we should bump the minimum Ruby version at least to 1.9.3.

But there are a few incompatibilities even with 1.9.3:

* If you run `bundle install` with 1.9.3, you get this error:

```

[!] There was an error parsing `Gemfile`:
[!] There was an error while loading `split.gemspec`: undefined method `metadata=' for #<Gem::Specification name=split version=3.1.0>. Bundler cannot continue.

 #  from /Users/pat/academia/projects/split/split.gemspec:15
 #  -------------------------------------------
 #
 >    s.metadata    = {
 #     "homepage_uri" => "https://github.com/splitrb/split",
 #  -------------------------------------------
. Bundler cannot continue.

 #  from /Users/pat/academia/projects/split/Gemfile:3
 #  -------------------------------------------
 #
 >  gemspec
 #
 #  -------------------------------------------
```

* If you comment out the `s.metadata =` lines, you get this error:

```
mustermann-1.0.1 requires ruby version >= 2.2.0, which is incompatible with the current version, ruby 1.9.3p551
```

* If you comment out Sinatra (which has Mustermann as a dependency), you get this error:

```
rack-2.0.3 requires ruby version >= 2.2.2, which is incompatible with the current version, ruby 1.9.3p551
```

There's probably a way of getting the dependency tree to work with 1.9.3, but it would be easier to bump the required Ruby version to 2.2.

What do you all think about which Ruby versions Split should support?

version | date
---|---
1.9.3|2011-10-31
2.0.0|2013-02-24
2.1.0|2013-12-25
2.2.0|2014-12-25
2.3.0|2015-12-25

**Comment by andrew** [comment]
My gut says to bump the minimum ruby version to 2.2.0 and stop testing against rails 4, anyone have any issue with that?

**Comment by henrik** [comment]
Maybe Rails 4.2+? 4.2 is the lowest Rails version that receives security updates: http://rubyonrails.org/security/ Also happens to be the version our monolith is currently on :)

**Comment by andrew** [comment]
Ok, let's go with  ruby 2.2.0 and up and rails 4.2 and up 👍

**Comment by andrew** [comment]
Just tested #498 on ruby 2.2.0p0 and 2.0.0-p645 and all the tests passed (had to deleted the local Gemfile.lock), also works on ruby 1.9.3 if you ensure the rubygems version is >= 2.0.0. 

Just pushed a branch that adds back in the support for 1.9.3: https://github.com/splitrb/split/tree/1.9.3-support

**Comment by andrew** [comment]
Just shipped v3.1.1: https://github.com/splitrb/split/releases/tag/v3.1.1 🚢
